### ISSUE TITLE
Filter On Storm HdInsight Bolt

### ISSUE THREAD

**Issue by Shriyanshmit** [Blackmist/eventhub-storm-hybrid#8]
Hi Blackmist,
Thanks for your quick reply on my previous threads.
I am using EventHubReader & EventHubWriter topology for accessing event hub, I want to add filter on Event Hub data accessing like Stream Analytics in azure. Is there any way to filter(using query or any other condition) data from Event hUb using Storm? If it is possible please let me know.  

Refrences: 
http://azure.microsoft.com/en-in/documentation/articles/hdinsight-storm-develop-csharp-event-hub-topology/

Thanks 
Shreyansh

**Comment by Blackmist** [comment]
The EventHubs API (https://msdn.microsoft.com/en-us/library/azure/dn790190.aspx) doesn't currently expose anything that lets you create filters on the receiving side. So you would need to read all events, and filter in your topology via code. This would involve creating a bolt that looks at the incoming data for whatever values you want to filter on. If the value is there, emit the tuple. If it's not, don't emit the tuple. You would still need to ack the tuple even if you don't re-emit it, as the spout would otherwise treat it as a failed tuple and replay it.
